# Dependencies
markdown: maruku
pygments: true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".gitignore", ".ruby-version", "CNAME", "LICENSE", "README.md", "Gemfile", "Gemfile.lock"]
port:             9001

url: https://revolutionprep.com
repo: https://github.com/RevolutionPrep/RevolutionPrep.github.io
